# Generated by Django 3.2.15 on 2022-09-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'OPEN'), (1, 'PENDING'), (2, 'RESOLVED')], default=0)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
