# Generated by Django 3.2.15 on 2022-09-11 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('Work Permit', 'Work Permit'), ('Critical Skill', 'Critical Skill'), ('Application Process', 'Application Process'), ('Stamp', 'Stamp'), ('Sponsorship', 'Sponsorship'), ('Qualifications', 'Qualifications'), ('Others', 'Others')], default='Others', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contr_users', to=settings.AUTH_USER_MODEL)),
                ('subject_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='queries.questionmodel')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
