# Generated by Django 3.2.15 on 2022-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('Work Permit', 'Work Permit'), ('Critical Skill', 'Critical Skill'), ('Application Process', 'Application Process'), ('Stamp', 'Stamp'), ('Sponsorship', 'Sponsorship'), ('Qualifications', 'Qualifications'), ('Others', 'Others')], default='Others', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
